name: CI Netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: netlify
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git rebase main
          git push
